### PR TITLE
BTH-10/ci-setup: added ci build.yml for building, testing and code linting using clippy. Created initial rust workspace

### PR DESCRIPTION
**Pull request by illia-st**

### CODE REVIEW

**Comment by illia-st** [comment]
Basically here added just a `build.yml` for testing and building

**Comment by Tr3tiakoFF** [comment]
Why do we need a `test_crate`?

**Comment by illia-st** [comment]
> Why do we need a `test_crate`?

In order not to make CI fail during the build. Will remove this crate #2

**Comment by Tr3tiakoFF** [comment]
> > Why do we need a `test_crate`?
> 
> 
> 
> In order not to make CI fail during the build

So I think it is better to delete it then

**Comment by illia-st** [comment]
> > > Why do we need a `test_crate`?
> > 
> > 
> > In order not to make CI fail during the build
> 
> So I think it is better to delete it then

Successfully deleted `test_crate` in #2

**Pull request merged**
